jobs:
  build:
    if: github.repository == 'Lihuanghe/SMSGate'
    runs-on: self-hosted
    services:
      redis:
        image: redis
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout
          5s --health-retries 5
        ports:
        - 6379:6379
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Config-RedisLongMessageFrameProvider
      run: echo 'com.zx.sms.common.RedisLongMessageFrameProvider' > src/test/resources/META-INF/services/com.zx.sms.codec.LongMessageFrameProvider
    - continue-on-error: true
      name: Change-TestConstants.Count
      run: echo 'TestConstants.Count=100000' >> src/test/resources/global.properties
    - continue-on-error: true
      env:
        REDIS_HOST: localhost
        REDIS_PORT: 6379
      name: Build with Maven
      run: mvn -B -DisReSendFailMsg=true test --file pom.xml
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
